source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'totalplay' do
  react_native_path = "../node_modules/react-native"
  pod 'yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path
  
  pod 'GoogleMaps'
end